// <auto-generated />
namespace WorkoutLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exerciseupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exerciseupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201506052018144_exercise-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
